name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Update to latest version

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3  # Update to latest version

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3  # Update to latest version

      - name: Log in to Docker Hub
        uses: docker/login-action@v3  # Update to latest version
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5  # Update to latest version
        with:
          context: .
          push: true
          tags: taanupal10/guestbook-go:latest
